// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtlVuXmH3jGFN5okFI5N8iQQmDQTQYnKU',
    appId: '1:477232001441:web:01c4873034902132355be0',
    messagingSenderId: '477232001441',
    projectId: 'terrarium-app-26837',
    authDomain: 'terrarium-app-26837.firebaseapp.com',
    storageBucket: 'terrarium-app-26837.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNT0p2R8mbCM7e__HYCWBWpPGUFmejlk8',
    appId: '1:477232001441:android:734b0f14be0bf653355be0',
    messagingSenderId: '477232001441',
    projectId: 'terrarium-app-26837',
    storageBucket: 'terrarium-app-26837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnJQvkY7GeMhwUZ2BycZBR6TS1iyl3Nms',
    appId: '1:477232001441:ios:cd22ee2aa24ebfbc355be0',
    messagingSenderId: '477232001441',
    projectId: 'terrarium-app-26837',
    storageBucket: 'terrarium-app-26837.firebasestorage.app',
    iosClientId: '477232001441-8eeud8res9s93kk64tv2noqmkmj85mpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.terraFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnJQvkY7GeMhwUZ2BycZBR6TS1iyl3Nms',
    appId: '1:477232001441:ios:cd22ee2aa24ebfbc355be0',
    messagingSenderId: '477232001441',
    projectId: 'terrarium-app-26837',
    storageBucket: 'terrarium-app-26837.firebasestorage.app',
    iosClientId: '477232001441-8eeud8res9s93kk64tv2noqmkmj85mpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.terraFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtlVuXmH3jGFN5okFI5N8iQQmDQTQYnKU',
    appId: '1:477232001441:web:4a4215344012cf11355be0',
    messagingSenderId: '477232001441',
    projectId: 'terrarium-app-26837',
    authDomain: 'terrarium-app-26837.firebaseapp.com',
    storageBucket: 'terrarium-app-26837.firebasestorage.app',
  );
}
